### ISSUE TITLE
Run browser-only notebook client?

### ISSUE THREAD

**Issue by NHDaly** [minrk/pypyjskernel#1]
This is so cool! 😃 

Is it possible to run the entire notebook via only static html/js files in the client? With this kernel, it seems like you could provide a notebook-like experience without needing a server at all!

(I'm imagining being able to write blog posts as a notebook, and just post them, and then they are themselves immediately interactive. Like you could read my blog post, then modify some numbers and rerun it to see the change, etc.)

Is that something that this kernel could make possible? :)

**Comment by minrk** [comment]
Possibly. I suspect the JupyterLab js will offer a more robust approach to trying that out.

**Comment by NHDaly** [comment]
Cool, thanks for the pointer! :)

**Comment by NHDaly** [comment]
Although, it looks to me like JupyterLab is still a server-hosted notebook application. I couldn't find anything on "JupyterLab js". Do you just mean their iJavaScript kernel?

**Comment by minrk** [comment]
The JupyterLab application does indeed use the same server as the existing notebook. But (unlike the earlier notebook), JupyterLab also provides javascript libraries which can be used to build different applications. What I mean is that the JupyterLab javascript libraries should allow you to more easily build an application that swaps out the interfaces that talk to the notebook server REST API for local javascript calls than the existing API, which is not meant to be able to swap out implementations of interfaces.
